### ISSUE TITLE
Index Validation

### ISSUE THREAD

**Issue by CalebKester** [granteagon/move#2]
Should this plugin prevent using negative values to be sent to the toIndex as well as values larger than the size of the array?

I'm not familiar enough with lodash to know if they put on data validations for this.

**Comment by granteagon** [comment]
My initial reaction is that passing in bad values is a code smell outside this function.  But I'm up for discussion.

**Comment by granteagon** [comment]
You might want to checkout my [granteagon/lodash-permute](https://github.com/granteagon/lodash-permute) repo which is a bit more mature than this one.
